sudo: false
language: node_js
node_js:
- '6'
- '5'
- '4'
os:
- osx
- linux
cache:
  yarn: true
  directories:
  - "$HOME/.npm"
before_install:
- yarn config set spin false
script: yarn cover
after_script: cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
deploy:
  provider: npm
  api_key:
    secure: YGm06omEBnbVtE3KI1KRKG7c2605Q7x2SDS0XAudWUmW8zII9utBTkpq6gkK4MTK6d4CESehwGEoubWeoQFn8YDQdHpA3iqMN1+PbJ89tszVD1Fg2oVofHHEQrqjT2t+QMc4mcNlJgz7e/WN5O6IfUOXJw7rmS0rDWw1qT/aO7kj51HT8+RfueKSsc9KYfM6t6act5XS0eAL71gpG9Cvwp6Ni+UcmtEEVPw8+8smoGkR0sqgWpeK5IdRWQsYjO0nkKoKu7vt5oBQMPpMsauivUDPxFVo0+OKzGOL3MikYvjMnTbbYjf/Ao0p4V+vUMKRfXZ2vhDEhLgIVOMac28uOt2WSoDcDoD8c4cfo/c6cPMpNUFx+XHxhirNYmnKZ1wDqmtMGzml6K7otBmAkUirT/I7aLXffppD4BDXANQMDNE7Faivje+kFgHWdJa3JelYTB5HnrQtRuEi58q25cBrJZXP3iB9wYR1tKHBcdR3LdTLFrEUnMB1MPdVgJhPGHwXQc8Fyo2zOuXENr7NPXMDSalwIKbHDQw/lDYBiMZMeCNIKKfiptfafaAod1FXWdG5Yzlfs7AsnDjV2EvRfWsjj5q4osxlgxCR79tQlcVn27amjL/4LPCA8ET1c6H6lNaKbGBV1M2zqQfaVUHMR9prmjgF7cqRk6yQMYrz9MK3B/0=
  email: dylan947@gmail.com
  on:
    tags: true
    repo: parch-js/orm
